export { default as Home } from './home'
export { default as About } from './about'
export { default as Work } from './work'
export { default as Skills } from './skills'
export { default as Contact } from './contact'